### ISSUE TITLE
Finalize AWS Shell configuration and Autoload

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#106]
- The AWS EC2 data model along with the AWS EC2 Instance deployment service data model are defined here - http://conf:8090/display/QP/AWS+-+design
Note that this page includes also the final attribute names and their descriptions. As part of this story we should make sure the data model in the package is as it appears in the design page.

- We need to provide a Shell Configuration XML as part of the OOB AWS shell. This shell configuration should include **all the AWS EC2 resource attributes.** 
**take into consideration " User input in shell template " ,if false it should not be visible .**

- The Autoload command that will be part of the AWS EC2 resource driver should be mocked, it should always pass and don't do anything (in a differently story we might implement some validations on the user input but it's out of scope for this story).
take a look at the vCenter

**Comment by alonagetzler** [comment]
this story is linked to story #157 in which we handle the behavior on app deployment when "storage size", "storage iops" and "root volume name" are empty (the value will be taken from the AMI).

**Comment by tornizanQ** [comment]
[Test](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=154933)
