### ISSUE TITLE
Un Clear error message in case of Power on perior to VM termination via the AWS

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/AWS-Shell#110]
![image](https://cloud.githubusercontent.com/assets/20166257/16378398/6eed09d4-3c74-11e6-8d55-100c228231e7.png)

**Comment by alonagetzler** [comment]
@yairbb i don't understand the bug. when powering on a VM we shouldn't throw an error but we just need to power on the VM... if it's already powered on we shouldn't throw an error as well (that counts as a successful "power on"). we should only throw an error if we tried to power on and something went wrong.

**Comment by yairbb** [comment]
If the VM was terminated via the AWS, Power on command shall returned specific Error like VM is terminated/ not available and not as mentioned above . this bug was entered as per Alex request.
