### ISSUE TITLE
When deploying 30 AMIs concurrently one AMI wasn't deployed

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/AWS-Shell#115]
Test Scenario: Deployment of 30 AMI's simultaneously.

Not all of them were deployed. ( 1 was skipped )

STR:

Have an environment with 30 undeployed apps with setup script
Reserve the environment

BIR:

29 from 30  were deployed.
 without powering them on. 

[QsLogs_QS-IL-YAIRB.zip](https://github.com/QualiSystems/AWS-Shell/files/338907/QsLogs_QS-IL-YAIRB.zip)

Related to Test case:Test Case 153412: Deploy 30 apps from AMI.

**Comment by alexazarh** [comment]
@yairbb 
Is it stable?

**Comment by yairbb** [comment]
Yes. 2 times.

**Comment by alexazarh** [comment]
Concurrency problem - opened bug 154812 in tfs

**Comment by alexazarh** [comment]
After investigation its not a concurrency problem in the server. Looks like the problem was resolved by changing the instance waiter to the default boto3 waiter.
The downside of this fix is that the default boto3 waiter pools every 15 sec when our custom waiter was polling every 2 secs

**Comment by yairbb** [comment]
Currently it seems like all the APPs were deployed correctly as as expected . from any reason not all of them are Active live status Grey.
Re-open this bug from that reason.

**Comment by alexazarh** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/6730546/17136683/74d6c218-533f-11e6-99b8-dc804512dcfc.png)
