### ISSUE TITLE
Run CheckoutFromPool from type NextAvailableIP with 10.0.1.0/24

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#117]
STR
Run this script:

jsonObject4 = {'Isolation': 'Shared',
              'ReservationId': '',
              'PoolId': 'PoolIP',
              'OwnerId': 'Tor',
               'SubnetRange':'10.0.1.0/24',
               'ReservedIPs': '',
              'Type': 'NextAvailableIP'}
NextAvaIP = json.dumps(jsonObject4)
qu = cloudshell.api.cloudshell_api.CloudShellAPISession('localhost','admin','admin','Global')
result = qu.CheckoutFromPool(NextAvaIP)
for x in range(255):
    result = qu.CheckoutFromPool(NextAvaIP)

BIR
After creating 10.0.1.192 the script is stopping and failing with error Could not find available IP.  while it is set on share and there is free ips till 10.0.1.255

**Comment by tornizanQ** [comment]
This bug is related to story #56 and it is blocking some test case

**Comment by alonagetzler** [comment]
the bug is - when trying the checkout an IP from the pool in a Shared isolation level and this IP is already checked out from the pool as Shared the method fails and says that the IP is already taken.

**Comment by tornizanQ** [comment]
Need to add to documentation that "NextAvailableIP" method is not supports "shared" as isolation type

**Comment by alonagetzler** [comment]
please resolve by adding to the method description the fact that it this method doesn't support Shared isolation type
