### ISSUE TITLE
Handle CVC with AWS - show error message

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#118]
need to make sure an error is thrown when trying to connect a CVC with an AWS as endpoint - that  it's not supported, and that all AWS apps within the same reservation are on the same subnet and are connected to each other

**Comment by alexazarh** [comment]
@alonagetzler what message should be displayed exactly?

**Comment by alonagetzler** [comment]
the message: "AWS EC2 apps don't support this type of connectivity. All AWS EC2 apps in the same Sandbox are on the same isolated subnet and can interact with each other."

**Comment by tornizanQ** [comment]
related bug: https://github.com/QualiSystems/AWS-Shell/issues/206
