### ISSUE TITLE
Keypair support in Guacamole

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#12]
- talk with Guacamole about keypair support
- figure out the changes needed to Guacamole integration (with Alex Abugov)

note that we'll have the PATH to the keypair in an attribute on the deployed app

**Comment by alexazarh** [comment]
Tomer has successfully  connected to a linux machine using a pem file with Guac.
We need to provide him a location of the path file that we plan to store in s3. He will implement the retrieval of the pem file in Java

**Comment by TCDooM** [comment]
Link creation in the portal:
will create SSH link using username/password if password field has value.
will create SSH using PEM file when no password value and there are the "region", "keypairs location" and the deployed in reservation is not null.

**Comment by alonagetzler** [comment]
need to check scenario with two guac servers, one in AWS for AWS apps and another local for vCenter/other resource in my on prem env. the links on resource should be created correctly per each guac server.

**Comment by alonagetzler** [comment]
we should test in this story:
- rdp/telnet/ssh for a windows machine
- rdp/telnet/ssh for a linux machine
- scenario with two guacamole servers in the same Quali server
- more?

**Comment by AdamSharon** [comment]
is VNC officially supported ? I know our guac server is generic enough to support it, but I don't know if there are many customers who use it (I know of one for sure). it requires deeper configurations.

**Comment by tornizanQ** [comment]
[test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=154810 )

**Comment by alexazarh** [comment]
Tomer c. completed this. 
AMI ID for QX is ami-fa16db9a in Oregon

**Comment by TCDooM** [comment]
Both Tomers. 😁
