### ISSUE TITLE
Apps Does not deploy in the reservation but created in AWS after setup script is ending with active with error

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#133]
STR 
Have an environment with setup script and an AMI app 
Reserve the environment 

BIR
An machine been created in AWS although the reservation is active with error and the machine was not created in the reservation

Logs
[Logs0707.zip](https://github.com/QualiSystems/AWS-Shell/files/351553/Logs0707.zip)

**Comment by alexazarh** [comment]
@tornizanQ  Can give more details how to reproduce this bug?
There is not way that it reproduces every time, there must be something unique about the app that you tried to deploy...

**Comment by tornizanQ** [comment]
nothing was unique about it, If I'm remember right there was some problem with retrieving data from AWS, but you can reproduce it by creating time out in the app

**Comment by alexazarh** [comment]
How do you create a timeout?

**Comment by alexazarh** [comment]
@tornizanQ please provide clear steps to reproduce or I will have to close this bug

**Comment by tornizanQ** [comment]
It was happening  because some problem with the connection to aws. I cannot reproduce the exact same scenario, can't we simulate timeout by code with sleep or something?

I guess it is the same scenario with the win credentials time out, maybe you can achieve it this way..
https://github.com/QualiSystems/AWS-Shell/issues/136
