### ISSUE TITLE
When app is not getting windows credentials the deploy is ending with time out error and the vm is not deplyed in the reservation, but a VM is created in AWS

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#136]
STR
Have a reservation with deployed bug 
Add an app from ami to the reservation that is unable to provide win credentials
Deploy the app and wait for timeout

BIR
The app deployment is ended with time out and the app is not been deployed in the reservation while in AWS the app is created and live.

**Comment by alexazarh** [comment]
@alonagetzler How we should resolve this?
terminate the instance OR continue with the deploy operation and leave the password attribute empty?

**Comment by alonagetzler** [comment]
continue the deploy operation

**Comment by tornizanQ** [comment]
Verified
