### ISSUE TITLE
when using custome AMI, AWS is not able to get windows credentials as a result our app is not getting win credentials and fail with time out

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#137]
STR
Have a reservation with deployed app 
Add undeployed app with costume AMI
Deploy the app

BIR
the deployment is failing with time out but vm is still created in aws

**Comment by alonagetzler** [comment]
we shouldn't fail when we can't get credentials

**Comment by alexazarh** [comment]
duplicate of #136
