### ISSUE TITLE
when having a deployed app connected to vlan in reservation with teardown script, when the reservation is ending the teardown is not running (Ticket 27834)

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#138]
STR
have environment with setup and teardown and app connected to auto vlan via CVC
Reserve the enviornment
end the reservation 

BIR
The reservation is not running teardown

**Comment by alonagetzler** [comment]
@tornizanQ just to be sure - you're talking about an AWS app, right? and the flow is having an app with CVC to Auto VLAN  in the blueprint --> reserve --> end reservation? or is the flow having an app --> reserve and wait for setup to end --> add CVC to VLAN --> end reservation?

bottom line, if there is a CVC between an AWS app to any other thing (VLAN / other app / resource) in a blueprint both the setup and the teardown should ignore the CVC and shouldn't fail. If user will try to press "connect" manually on the CVC (regardless if the AWS app is deployed or not) he should get a message that this type of connectivity isn't supported for AWS apps.

**Comment by tornizanQ** [comment]
its about the Jim ticket

**Comment by alexazarh** [comment]
@alonagetzler - he is referring to vCenter app. This issue is related to ticket 27834.
And if there is a CVC between an AWS app to any other thing in a blueprint both the setup and the teardown WILL FAIL. The behavior that you are describing cannot be implemented in 7.1

**Comment by alexazarh** [comment]
Fixed with changesets:  155604 & 155605
