### ISSUE TITLE
Pool API :: NextAvailableSubnet

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#14]
1) NextAvailableSubnet 
- need the ability to have a subnet (CIDR) as an item in the pool
- need a NextAvailableSubnet selection criteria, which gets a size as an input and allocates the next subnet from the pool (the pool id is region id)
- the owner of the subnet should be empty
- the subnet item can be taken from the pool as shared or exclusive

**Request example:**
```
{ 
  type: NextAvailableSubnet,
  poolId: region id
  ownerId: ??
  reservationId:
  Isolation: exclusive / shared
  Exclusions:CIDR that should be excluded (reserved)
}
```

* SubnetRange is an attribute on the EC2 resource. It should come with a default value

* update JSON schema accordingly:
http://conf:8090/display/QP/GenericPool+Api+JSON+Schema

**Comment by GilGald** [comment]
The CIDR will be always calculated with 255 bits. aka /24
so the range will be for example:  x.y.0.0 to x.y.0.255

**Comment by alonagetzler** [comment]
what do you mean by always with 255 bits? we should be able to support allocate other sizes of ranges (of size 2^n)

**Comment by tornizanQ** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=154381)

**Comment by alonagetzler** [comment]
regarding my previous comment, that's OK that CIDR we allocate for VPC and subnet is 255 for now

**Comment by tornizanQ** [comment]
Unable to check if  "Share" isolation is working correctly, is there any idea how to check it efficiently?

**Comment by tornizanQ** [comment]
Blocked by P2 bug
