### ISSUE TITLE
When deploying a new app from aws the storage is set by the ami default and not the attributes

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#143]
STR
Have a reservation with deployed AWS app 
Add undeployed app and set a new private AMI with known storage size and iops that are not the default once.
Deploy the app

BIR
The storage size of the deployed vm is the same as the ami and not the app attribute

![image](https://cloud.githubusercontent.com/assets/17527106/16761143/91ad9d6c-4827-11e6-829d-449b793de765.png)

**Comment by alexazarh** [comment]
This is aws built-in functionality. You cannot set lower storage size than the default of the ami
