### ISSUE TITLE
NextAvailableSubnet type is not working as shared when configured as shared and all the available subnets are already reserved as shared

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#144]
STR
Have this db (\\qsnas1\Shared\Tor\db) installed as your db 
Run checkoutfrompool command with shared
isolation, and 't' as poolid 

BIR 
an error returns although all the subnets are shared,

Logs:
[TeamServer.Service.txt](https://github.com/QualiSystems/AWS-Shell/files/357086/TeamServer.Service.txt)

**Comment by GilGald** [comment]
same fix as this bug :
https://github.com/QualiSystems/AWS-Shell/issues/117
we'll change the exception of the api.
we cannot use shared isolation on subnets.
