### ISSUE TITLE
when deleting resource not from reservation (inventory) the delete command is not called

### ISSUE THREAD

**Issue by AdamSharon** [QualiSystems/AWS-Shell#145]
1. delete a deployed app not from reservation (inventory\RM)

the "delete" command in the reservation is not called.

**Comment by alonagetzler** [comment]
according to Alex: From the error I think that the Delete command does gets called and it fails if the deletion is not in the context of a reservation.

**Comment by alexazarh** [comment]
The problem is that the delete command doest work when called not in reservation context

**Comment by TaiTheGreat** [comment]
@AdamSharon @alonagetzler So is this a bug? What do we do with this?

**Comment by alonagetzler** [comment]
@tornizanQ so does it call the delete command or not? if it doesn't it is still a bug..
