### ISSUE TITLE
Deploying an app (post-setup) when no SG exists for the reservation displays unclear error message

### ISSUE THREAD

**Issue by TaiTheGreat** [QualiSystems/AWS-Shell#147]
1. Have an AWS reservation. 
2. Add an app to it.
3. In the AWS console, delete the SG of the reservation (terminate any existing instances if you must).
4. Try to deploy the app. 

BIR if you receive a "attribute error", where "NoneType" object has no attribute ID

**Comment by alonagetzler** [comment]
@TaiTheGreat does this bug happen also when trying to deploy an app in a reservation that didn't have setup? or only when you manually go and delete the SG from AWS?

**Comment by TaiTheGreat** [comment]
@alonagetzler  Nope, only when deleting the SG.
