### ISSUE TITLE
Interface for getting Sandbox VPC information (documentation only)

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#150]
we want to expose the Sandbox VPC information (VPC CIDR, VPC ID, Sandbox SG etc.) to the orchestration developer so they'll be able to dynamically connect the Sandbox VPC to some another location (on prem?)

**Comment by alonagetzler** [comment]
need to consider solving this requirement by documenting the usage of the reservation Id tag in AWS BI

**Comment by menib** [comment]
Not all customers purchased the BI package, I think we should solve by printing to the output console.

**Comment by alexazarh** [comment]
@menib The idea here is to document the tags that we use so that if you develop your own automation you an use this tags as well to find the relevant resources.

**Comment by TomerAdmon** [comment]
We will fix this bug/feature by adding documentation explains that in order to get more information about the network, it's possible to search for a vpc with the reservation id tag and get the vpc information.

--NEED DOCUMENTATION--

**Comment by TomerAdmon** [comment]
It's possible  to use the AWS api  to search for VPC name with the sandbox Id  to get information about the sandbox VPC during the Sandbox lifecycle for automation processes.

**Comment by Shnitselon** [comment]
added the following note to the "AWS Integration" topic:
Amazon API enables you to retrieve a sandbox's VPC name using the ReservationId tag with the sandbox's ID. This can be used, for example, in real-time automation processes.
