### ISSUE TITLE
Trying to remove AWS deployed app by api commands (DeleteResource, RemoveAppFromReservation) ends with an error

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#152]
STR
Have a reservation with deployed app in it 
Open api session in python 
Run command DeleteResource or  RemoveAppFromReservation

BIR
The command failed to run and the app is still active

Logs
[TeamServer.Service.txt](https://github.com/QualiSystems/AWS-Shell/files/361150/TeamServer.Service.txt)

**Comment by alexazarh** [comment]
duplicate of #145
