### ISSUE TITLE
Power off Autoload VM will be turned on by environment setup scritp

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#156]
STR
Have an environment with powered off autoloaded VM and a setup script
Reserve the environment 

BIR
The autoloaded VM is been powered on by the setup script but it shouldn't

**Also occurs when  teardown script is running, Autoload vms will be shut off

**Comment by alexazarh** [comment]
The setup & teardown scripts will ignore resources that were not created in the context reservation. It means it will ignore it for power on/of, connectivity, delete
