### ISSUE TITLE
Separating management VPC ES to two different instances with differnt roles

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#158]
The 1st ES is the one we will use for  creating the sandbox vpc and instances (will be associated with the AWS EC2 resource)
---> this ES should have the role with AWS permissions

The 2nd ES is the one that will be used for running instillation script + commands on the instances (will be associated with the deployed app)
---> this ES should just be able to access the instances in all the peered VPCs (the sandbox VPCs)

this story is linked to story #36 and affects the CloudFormation JSON

**Comment by yairbb** [comment]
@alonagetzler 

Are there any special Requirements regarding the second one ?
I reffer to the instance private IP , SG1 , Inbound ,  Outbound and etc.

**Comment by tornizanQ** [comment]
Test under https://github.com/QualiSystems/AWS-Shell/issues/36
