### ISSUE TITLE
App deployed but the instance still in intializing status

### ISSUE THREAD

**Issue by GilGald** [QualiSystems/AWS-Shell#172]
After the app deployed the instance in aws in running state but the status is initializing.
It should be in OK status.

**Comment by alexazarh** [comment]
Here is how to get health chek status:
http://boto3.readthedocs.io/en/latest/guide/migrationec2.html

**Comment by alexazarh** [comment]
this can be another way to solve this:
http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Waiter.InstanceStatusOk

**Comment by GilGald** [comment]
what are status checks
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-system-instance-status-check.html

**Comment by GilGald** [comment]
http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstanceStatus.html
