### ISSUE TITLE
Can't deploy AMIs from the marketplace

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#186]
additional "approval" step is required and the deploy fails

**Comment by GilGald** [comment]
![2](https://cloud.githubusercontent.com/assets/15359652/17084848/6d89b87c-51d1-11e6-8ec0-7b85e9fc140d.jpg)
![1](https://cloud.githubusercontent.com/assets/15359652/17084849/6da5046a-51d1-11e6-8fc9-32aa6a34c150.png)
