### ISSUE TITLE
Shouldn't show message in output when there is nothing to disconnect on teardown

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#191]
steps to reproduce:
1. have an environment with OOB setup and teardown and some apps (no connections)
2. reserve the environment
3. wait for the apps to be deployed
4. end the reservation

bug is reproduced if there is a message in the output console "nothing to disconnecting". there shouldn't be any message to the console about this case.

![image](https://cloud.githubusercontent.com/assets/16175869/17024155/75f7f150-4f5f-11e6-9c8e-8ac5eecbc2d4.png)

**Comment by TaiTheGreat** [comment]
@alexazarh Still reproduces on a clean DB after deleting the shell from Drop and importing the latest.

**Comment by alexazarh** [comment]
You need to import the cloudhshell-orch-sandbox to get the latest teardown scripts
