### ISSUE TITLE
Need to update the AWS shell configuration that address isn't required

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#194]
The shell configuration that comes with the AWS shell shouldn't require address but it currently does and the user must fill in some value although it doesn't makes sense. In order to hide the address field a tag should be added "AddressRequired = "false""

![image](https://cloud.githubusercontent.com/assets/16175869/17082589/2f32134c-518d-11e6-825b-7de0a1a15127.png)

**Comment by TaiTheGreat** [comment]
@alonagetzler  Default is still to show address field, but adding the tag removes it.

**Comment by alonagetzler** [comment]
@TaiTheGreat @alexazarh --> the whole point of this bug was that the OOB shell configuration that comes with 7.1 won't require the user to fill in the address, so it should include the tag. please close the bug only after the tag is included and the AWS shell configuration doesn't require entering the address

**Comment by TaiTheGreat** [comment]
Ah. Will do.

**Comment by TaiTheGreat** [comment]
@alexazarh was this fixed to be automatically displayed without an address?

**Comment by TaiTheGreat** [comment]
Fixed on clean DB with latest Shell.
