### ISSUE TITLE
When installation script fail to run successfully the app is deployed without live status

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#196]
STR
Have an environment with setup script and undeployed app linked to a "problematic" installation script 

BIR
the app is deployed without live status.

![image](https://cloud.githubusercontent.com/assets/17527106/17082639/a9978800-518e-11e6-982a-e20d2632ef36.png)

**Comment by alexazarh** [comment]
Resolved with changeset 156630 in tfs
