### ISSUE TITLE
The default value of the auto events attribute should be TRUE and not FALSE

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#199]
The current default value in the attributes bank of the attributes Auto Power On, Auto Power Off, Auto Delete and Autoload is False, should be True

![image](https://cloud.githubusercontent.com/assets/16175869/17082897/2c9fa9b0-5196-11e6-8927-2c2d0c9232c0.png)

**Comment by alexazarh** [comment]
We removed "Auto Delete" + "Auto Power On" + Auto Power Off" from aws.
Fixed this for Autoload and also fixed for all attributes in vcenter.
