### ISSUE TITLE
Delete Instance command

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#20]
Terminate the AWS instance only
this command should be hidden and will be called by RemoveResourceFromReservation

we should delete all entities related to this instance as part of this command.
For now only delete the exclusive Security Group. 
The deletion of storage will be handled in another story.

**there will be only a hidden command! no command exposed to the user.
**need to consider supporting bulk deletion using this command (should be aligned with the Server)

**Comment by TaiTheGreat** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=153935)

**Comment by tornizanQ** [comment]
Waiting for blocking bug: (#24)[https://github.com/QualiSystems/AWS-Shell/issues/124] to be fixed

**Comment by tornizanQ** [comment]
Is there any api method to delete app? 
The method delete resource is not working on deployed apps as it seems when I try to run it manually from python cloudshell api

**Comment by alonagetzler** [comment]
you should use either "RemoveResourcesFromReservation" or "DeleteResources", and both should work (if not that's a bug for Shay's scrum)

**Comment by tornizanQ** [comment]
Blocking bug
https://github.com/QualiSystems/AWS-Shell/issues/83
