### ISSUE TITLE
capitalization of messages to output widget during setup and teadown is inconsistant

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#220]
Consistency with capital letters (fix the last line)
![image](https://cloud.githubusercontent.com/assets/17527106/17208009/a201110e-54bf-11e6-97ff-c7b0a75bc512.png)

**Comment by alexazarh** [comment]
According to the image the problem is in the single app deployment orchestration not in the setup or teardwon. It was fixed in the single app orchestration.
