### ISSUE TITLE
Assigning an associated Elastic IP to an AMI displays the wrong info on the error

### ISSUE THREAD

**Issue by TaiTheGreat** [QualiSystems/AWS-Shell#229]
1. Create an elastic IP. 
2. Assign it to an AWS app.
3. Reserve and wait for the app to receive the IP.
4. Reserve the same environment for the second time, while making sure the app still has the same IP assigned to it.

BIR if the error states that the allocation ID is already in use instead of the actual IP.

**Comment by TaiTheGreat** [comment]
![image](https://cloud.githubusercontent.com/assets/18596231/17276610/a7e5b966-5736-11e6-82d1-5d0d096d029b.png)

**Comment by alonagetzler** [comment]
this flow won't be possible anymore after the change in behavior of the Elastic IP allocation
