### ISSUE TITLE
"Orchestration Save" command output missing it identifier attribute value

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#233]
STR
Have a reservation with a deployed vCenter app 
Change the hidden command category of the vcenter shell driver to be regular category
Run the Orchestration Save command

BIR
the command ran and have an output 
the output attribute identifier is missing it value.

workaround 
use the "get snapshot" command and use it out put as the identifier

**Comment by alonagetzler** [comment]
#tornizanQ i'm not sure i understand this bug. what do you mean by "identifier"? which identifier? what's the user flow that is blocked here?

**Comment by tornizanQ** [comment]
There is  an attribute in the output JSON named  "identifier" and he hasn't got a value and you can't use  the restore the snapshot snapshot command without it

Boris already knows about it and working on it

**Comment by tornizanQ** [comment]
Boris said that there are some of Shay tests that are blocking the code from merging to the suite,

**Comment by alonagetzler** [comment]
@tornizanQ so the flow is just trying to use the "Restore Snapshot" command? it doesn't work in 7.1 EA? so why this bug isn't P1??

**Comment by alonagetzler** [comment]
The bug is that the orchestration_save command doesn't output the name of the created snapshot. The orchestration_restore works, but expects a JSON that currently the orchestration_save doesn't output.
