### ISSUE TITLE
Save Snapshot have empty output

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#234]
Have an reservation with vcenter app 
run save snapshot command

BIR
there is empty output from the command that need to be removed.
![image](https://cloud.githubusercontent.com/assets/17527106/17289118/e12b3ca0-57e0-11e6-8572-c9f5ccb6c064.png)

**Comment by alexazarh** [comment]
@tornizanQ 
Should the save snapshot command return a value in any any scenario? Or its always should be void?
