### ISSUE TITLE
typo in activity message

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/AWS-Shell#247]
when there is nothing to disconnect during teardown the message that apears in activity feed is:
 'nothing to disconnecting'
should be:
nothing to disconnect

**Comment by alonagetzler** [comment]
we have another issue about that
we shouldn't show this message at all, not just fix the typo

**Comment by alonagetzler** [comment]
@yairbb  please check if this still reproduces, i'm not sure that the message is there

**Comment by yairbb** [comment]
Indeed. There is no such a message.
