### ISSUE TITLE
Allocate Elastic IP instead of getting it from the app designer

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#250]
need to change the Elastic IP attribute from string to boolean (and rename to Add Elastic IP) and create a new elastic ip when the app is deployed + delete it when it is destroyed. The default for this attribute should be false (not allcoate elastic ip by default). the behavior of posting the elastic ip in the public ip attribute on the deployed app should remain.

flow:
1. on deploy - (a) create elastic ip (b) associate with the machine
2. on delete - (a) delete the elastic ip

note - we should remove the old Elastic IP string attribute and the logic associated with it.

we will need to show a clear error in case the Elastic IP limit has been reached for the account region.

**Comment by yairbb** [comment]
Minor Remark: Actually the field was rename as " Allocate Elastic IP" and not "Add Elastic IP".

**Comment by yairbb** [comment]
(Test Plan)[http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=156849]
