### ISSUE TITLE
Security Group does not exist

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/AWS-Shell#253]
SG not ready in AWS after creating it.

Attached link:

file://qsnas1/Engineering/Builds/Tests/ServerLogs/2016_08_10/Removing_The_App_Deletes_The_Custom_SG_Includ_The_Inbound_And_Outbound_442153939607.log.txt
« Hide stacktrace

**Comment by alexazarh** [comment]
This also happens with Internet Gateways and Subnets in the setup
