### ISSUE TITLE
Error trying to connect 10 VLAN par reservation with 3 reservation in parallel using setup script

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/AWS-Shell#256]
STR:

1. use the DB in the bug and reserve the environment "VLAN 10 PORT TEST" 3 times in parallel 

bug reproduce:

when connecting the vlan you will get an error Description: Failed to wait for the command execution to end:

Related to Elads bug:
http://team:8080/tfs/Quali-Collection/QualiSystems/_workitems/edit/155226

**Comment by yairbb** [comment]
[logs.zip](https://github.com/QualiSystems/AWS-Shell/files/413465/logs.zip)

[eladDB (3).zip](https://github.com/QualiSystems/AWS-Shell/files/413470/eladDB.3.zip)

[eladDB (4).zip](https://github.com/QualiSystems/AWS-Shell/files/413471/eladDB.4.zip)
[Uploading eladDB (5).zip…]()

[Uploading eladDB (6).zip…]()
[Uploading logs.zip…]()
[Uploading eladDB (7).zip…]()
[Uploading eladDB.zip…]()
[Uploading logs (2).zip…]()
[Uploading eladDB (2).zip…]()

**Comment by alexazarh** [comment]
Cannot reproduce bug
