### ISSUE TITLE
If one command get timeout all requested connection get failed to connect

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#263]
Have an environment with several connectivity providers - two switches and a vcenter.
All of the vcenter and the other switch commands concluded successfully. One switch timed out and everything showed as disconnected.

**Comment by alonagetzler** [comment]
The error that should be returned to the Setup in such scenario should be: "One or more of the connection requests timed out, see failed indication on the relevant connection(s)."

**Comment by alexazarh** [comment]
Resolved with changeset 157203
