### ISSUE TITLE
Pool API (7.0)

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/AWS-Shell#27]
1) CheckOutFromPool
Inputs:
- isolation level - shared, exclusive
- selection criteria type - specific numeric, next available numeric, specific numeric range, (TBD - next available range)
- selection criteria parameters - JSON object  
- pool id
- reservation id
- owner id

Output:
string array
- not empty string
validations in api:
- Reservation id is valid - active/pending res
- owner id 

2) ReleaseFromPool
- item value
- pool id
- reservation id
- owner id

Outputs: TBD

* All fields are mandatory

* Create a conf page with the JSON schema for every supported selection criteria type
* In the xml doc create the APIs as internal (ask Roni how to do it)

**Comment by alexazarh** [comment]
Note: during the refactor need to resolve bug #690 (vCenterShell repo)

**Comment by alexazarh** [comment]
Need to generate new Cloudshell Automation API
