### ISSUE TITLE
create releases for 7.1 GA

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#271]
Need to create release tags for CloudShell 7.1 GA for the following repositories:
- aws-shell => minor release
- vcenter-shell => minor release
- cloudshell-orch-sandbox => minor release

**Comment by yairbb** [comment]
Community certified items - release management Static VM. on PV Team Responsibility

**Comment by alexazarh** [comment]
Created release branches for aws & vcenter
aws - v1.0.1
vcenter - v1.3.1

**Comment by alexazarh** [comment]
Releases created, still need to create offline package
