### ISSUE TITLE
Unclear error when power on command fails

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#288]
STR
have an aws machine in reservation 
Terminate the machine from AWS 
Run power on command 

BIR
unclear error appears
maybe add the same error as power off

![image](https://cloud.githubusercontent.com/assets/17527106/18462756/d2257792-798d-11e6-8bf6-110f7341c716.png)

**Comment by alexazarh** [comment]
@tornizanQ please check if we have a duplicate

**Comment by alexazarh** [comment]
@tornizanQ  If think #110 is the duplicate

**Comment by tornizanQ** [comment]
duplicated
