### ISSUE TITLE
Update CF to support version selection for ES installation

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#299]

**Comment by nahumtimerman** [comment]
1. User selects Cloudshell Version from a parameter when using Cloudformation
2. During instance launch, execution server binary of selected version will be downloaded from S3
3. Downloaded execution server binary will be configured and will start running on mono

**Comment by nahumtimerman** [comment]
1. For each supported Cloudshell Server version, there is a folder with cloudformations and exec.tar in S3
2. The user activates cloudformation with the main.json or main_ex.json from the S3 folder of Cloudshell version X.X.X;
3. main.json calls EC2 json which creates instances of Execution Server (shells and commands).
4. After instances are created, they immediately run a script:
a. set DNS to google dns.
b. download exec tar from S3 version folder to root/ExecutionServer/
c. uncompress exec tar
d. download updated cf_config_ex from s3
e. cf_config_params parameters file is created
f. supervisor service restarts execution server service

Troubleshooting:
logs for the executable which runs EX service should be created in /var/log/cf_config.log.
If there is any problem with downloading from S3, check the logs /var/log/cloud-init.log

**Comment by alexazarh** [comment]
related: https://github.com/QualiSystems/Azure-Shell/issues/282
