### ISSUE TITLE
Deploy AWS Instance from AMI

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#3]
goal: add "AWS EC2 Instance" deployment option to an app, fill in an AMI and launch an AWS instance (use defaults for all parameters) in the region defined on the AWS EC2 resource.

no installation yet, no power on

the instance should get a public ip once deployed (the public ip is att on deployment option) and it should be stored in its address. 

For now add a dynamic private .

how to demo: create an app, select "AWS EC2 instance", enter AMI ID, add app to a reservation, hit "Deploy", see the app being replaced with a deployed app and an AWS Instance created (the Instance ID should be stored in the VM Properties, along with the Cloud Provider name).  the subnet should be some default subnet in the VPC in this stage.

The instance should be powered off by default.

in order to create an instance generate a keypair per instance, and store it locally on the ES (temp)

* add tags to the deployed instance. What tags? - TBD

**Comment by tornizanQ** [comment]
http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=153394
