### ISSUE TITLE
QualiX 2.4 - update AWS CF AMI to install latest QX

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/AWS-Shell#314]

**Comment by TomerAdmon** [comment]
need to talk with Edan how to prioritize this task.

**Comment by alexazarh** [comment]
Update AWS CF to use Centos 7.2 AMI from the marketplace and using the "user data" feature execute the installation of QualiX.
The user data code should download the QX installation script from a static path and run it. We would like to use the same installation script that we have in Azure. So in case we 
need to modify it we need to make sure it works both on Azure and AWS.

http://confluence.quali.com/display/QRND/QualiX+2.4+-+Deployment+script

Note: the user data code might be executed before internet connectivity is available.  We need to make sure that we have a retry loop similar to what we have in the execution server installation.

**Comment by alexazarh** [comment]
@TaiTheGreat I deployed a stack in the Ohio region. You can check the QualiX there.
