### ISSUE TITLE
logic to identify the first app

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#35]
when deploying an app (not via setup) is should be able to identify if that's the first app. if it is it should call the pool and get VPC and Subnet allocation. if it isn't is should use existing VPC and Subnet allocated to this reservation.

tech note - need to sync between deployment threads

**Comment by alexazarh** [comment]
This is not required. The preparation of the sandbox will be done in the setup of the reservation. If you will try to deploy an aws app without the setup running you should get an error
