### ISSUE TITLE
Create cloudformation json to create the management network

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#36]
Notes:
--------
-	We will publish two public AMIs for QualiX and ES, which should be accessible per each region

Management VPC:
------------------------
Option 1 – private deployment (QualiX with private IP):
1.	Instance QualiX
a.	Should have only private ip by default
b.	Associated both with SG1 and SG2
c.	Inbound – port 80
d.	Outbound that will allow the ES to contact the Quali Server + License Server (allow all?)
2.	Instance of ES
a.	Should have internet access (to be able to download python packages from pypi)
b.	Should have only private ip
c.	Associated only with SG1
d.	Inbound – no
e.	Outbound – all traffic
3.	NAT in the VPC
4.	Both instances need an IAM role to access AWS API (the role name should contain “CloudShell”)
5.	Anything needed for VPN configuration
6.	SGs:
a.	SG1: Inbound – no, outbound – all
b.	SG2: inbound – port 80
7.	Optional - S3 endpoint
8.	Tags on all entities:
a.	CreateBy = CloudShell
b.	Role = Management
9.	S3 bucket for PEM files (name should be “CloudShell Sandboxes <accountNumber>”)

Option 2 – public deployment (QualiX with public IP):
1.	Instance QualiX
a.	Should have a public ip by default (elastic ip)
b.	Associated both with SG1 and SG2
c.	Inbound – port 80
d.	Outbound that will allow the ES to contact the Quali Server + License Server (allow all?)
2.	Instance of ES
a.	Should have internet access (to be able to download python packages from pypi)
b.	Should have only private ip
c.	Associated only with SG1
d.	Inbound – no
e.	Outbound – all traffic
3.	Internet Gateway in the VPC
4.	Both instances need an IAM role to access AWS API (the role name should contain “CloudShell”)
5.	Anything needed for VPN configuration
6.	SGs:
a.	SG1: Inbound – no, outbound – all
b.	SG2: inbound – port 80
7.	Optional - S3 endpoint
8.	Tags on all entities:
a.	CreatedBy = CloudShell
b.	Role = Management
9.	S3 bucket for PEM files (name should be “CloudShell Sandboxes <accountId>”)

Installation + configuration after VPC management is up
----------------------------------------------------------------------
1.	Configure the VPN on the router
2.	need to configure ES to QualiServer+LicenseServer, maybe we can do that automatically
3.	need to configure server universal settings XML on the Quali Server to point to the QualiX
4.	Execution Server Selector value should be created for each region, and associated in CloudShell with the new ES

User input/output
-----------------------
input from the admin will be:
1.	AWS region
2.	(AMI ID of QualiX and ES AMIs in the region  can be mapped)
3.	Credentials
4.	(user has access to the on-prem router for VPN configuration)
a.	Public IP of the router
b.	IP address range of a network behind the router that can access Quali Server and License Server and any other client that needs access to QualiX. 
5.	QualiServer and LicenseServer address in the on-prem network
6.	Management VPC CIDR
7.	ES numbber of slots (same input for both ES's) 

output of the management VPC that the admin will use:
---------------------------------------------------------------------
-	Management VPC ID
-	SG1 ID
-	S3 bucket name (name should be “CloudShell Sandboxes <accountId>”)
-	Optional - Elastic IP of QualiX
-	Optional - VPN configuration

Flow for admin
-------------------
1.	Deploy JSON
2.	Configure VPN in the on-prem side
3.	Restart ES
4.	Steps 3-4 in the installation+configuration above

**Comment by alonagetzler** [comment]
we decided to separate the ES to two ES instances, one that will be used to created the sandbox VPC and instances and another that will be used to run installation script and commands on the instances. see details in story #158

**Comment by yairbb** [comment]
1)  The external deployment also requires vpc configurations. Its missing at the moment.
2)  Internal Deployment- Add Private IP of Qualix.
3) Default CIDR values: 
    3.1) VPCCIDR: "10.0.0.0/24"
    3.2) Internal subnet CIDR should be derived accordingly
4) Updated user guide with deployment that contains VPN configurations
5) Nat Instance Size input should be removed
6) SlotsNumber  input should be removed and the default should be 100
7) KeyPair?

**Comment by tornizanQ** [comment]
(Test)[http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=154820]

**Comment by alexazarh** [comment]
What left to do:
- Finalize ES ami
- Update ami / region mapping
- Set correct instance size for QualiX and ES
