### ISSUE TITLE
Support Power On/Off commands for a deployed Instance

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#4]
Power On = Start
Power Off = Stop/Terminate

we should have an attribute on the AWS EC2 resource called "Shutdown Type" with Stop/Terminate options. The power off should use this attribute to determine the shutdown type.

** check that we don't conflict with vCenter Shell

**Comment by tornizanQ** [comment]
[TestPlan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=153482)
