### ISSUE TITLE
Get credentials for an Instance deployment - Windows

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#5]
we need to be able to get the Instance credentials so a user will be able to RDP/Telnet/SSH a deployed instance.

The credentials should be saved  in attributes on the deployed app (User, Password) +  in the VM properties (password should be a string in the VM properties) so an API user can get them.

Tech note:
Make sure that the GetWinCredentials api call still works even when the AWS AMI Config  service is disabled when using a private AMI

**Comment by tornizanQ** [comment]
(Test Plan)[http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=154448]

**Comment by tornizanQ** [comment]
Related blocking bug:
https://github.com/QualiSystems/AWS-Shell/issues/136
