### ISSUE TITLE
Rename aws package name

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#50]
The name of the current package is "aws_shell_driver.zip". 
Should be rename to "AWS-Shell.zip"

**Comment by GilGald** [comment]
we need to change the name to : aws_shell not to  AWS-Shell
the files that need to changed are:
C:\work\Git\AWS-Shell\drivers\aws_shell_specs\aws_shell.ini
C:\work\Git\AWS-Shell\drivers\aws_shell_specs\deploy_aws_ec2_ami_instance.ini
C:\work\Git\AWS-Shell\drivers\aws_shellPackage\Configuration\shellconfig.xml
C:\work\Git\AWS-Shell\drivers\aws_shellPackage\DataModel\AWS.png
C:\work\Git\AWS-Shell\drivers\aws_shellPackage\DataModel\datamodel.xml
C:\work\Git\AWS-Shell\drivers\aws_shellPackage\DataModel\shellconfig.xml
C:\work\Git\AWS-Shell\drivers\aws_shellPackage\metadata.xml
C:\work\Git\AWS-Shell\drivers\install.bat
C:\work\Git\AWS-Shell\drivers\pack.bat
