### ISSUE TITLE
Update Teardown to use new server API for resource deletion

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/AWS-Shell#51]
related to Product Backlog Item 153342:Remove deployed resource from reservation via API

need to update teardown script to call RemoveResourceFromReservation instead of DeleteResources

**Comment by alexazarh** [comment]
Teardown script updated in private branch, waiting to get feedback if it works before merge to develop.

@alonagetzler We also should remove the Delete command from vCenter & AWS shells when Shay's team finish this story?

**Comment by alonagetzler** [comment]
@alexazarh  we should. the command should be only the one that deletes the VM itself and it should be hidden (it will be good if its name can be "Delete VM From Cloud Provider Only" and not just "Delete")

**Comment by TaiTheGreat** [comment]
@alexazarh @alonagetzler Is this still relevant, or is it covered by the "delete instance command" story?
Also, if it's not covered, does it require manual testing? or just seeing that teardown actually deletes everything?

**Comment by alexazarh** [comment]
In this story I think you need to verify that the teardown deletes the apps with the new flow using RemoveResourceFromReservation api
