### ISSUE TITLE
CleanupSandboxConnectivity command

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/AWS-Shell#52]
1) Add  CleanupSandboxConnectivity  cpmmand to aws shell. The command will get a json string:
{
  reservation_id: "guid"
}
2) The command will delete the VPC (and peering to management vpc), Subnet and Sandbox SG that are tagged with the reservation id. 
And also delete the sandbox keypair from s3
* Note: if there are any instances of ec2 machines in the VPC than also terminate them and also other entities that might prevent us from removing the vpc
* Dev note: this must be bulletproof. Maybe add reties.

Flow:
---------
this story is about part 3 of the flow.
(1) teardown --> (2) CleanUpSandboxConnectivity API --> (3) CleanUpSandboxConnectivity command in the shell

**Comment by doppleware** [comment]
@alonagetzler  
Do we want to hard cleanup the VPC? It means deleting everything in the VPC also including stuff not created by Quali?

**Comment by alonagetzler** [comment]
@alexazarh what kind of stuff can be in the VPC that is not created by us? isn't the whole VPC is created by us?

**Comment by alexazarh** [comment]
Yes the whole VPC is created by us, but the admin can create an instance or security groups manually and place it in our VPC for example

**Comment by alonagetzler** [comment]
so yes, we want to hard cleanup the VPC, including everything that wasn't creating by us under this VPC

**Comment by alexazarh** [comment]
Also going to add removal of internet gateway

**Comment by TaiTheGreat** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=154530)
