### ISSUE TITLE
Pool API :: NextAvailableIp

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#56]
2) NextAvailableIp

{ 
type: NextAvailableIP,
poolId: aws subnet id
ownerId:, cloudshell resourceName
Isolation: exclusive / shared
reservationId: reservationId
SubnetRange: { CIDR of the allocation range }
ReservedIPs: [ip1, ip2]
}

* update JSON schema accordingly:
http://conf:8090/display/QP/GenericPool+Api+JSON+Schema

**Comment by tornizanQ** [comment]
Test Plan 
http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=154292

**Comment by tornizanQ** [comment]
Bug P2 (#117) was opened
