### ISSUE TITLE
Investigate how to create a powered off instance in AWS

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#58]
We want the instance to be powered off when we create it in aws shell

**Comment by alexazarh** [comment]
@alonagetzler 
From what I read its not possible to create an instance in a stopped state. When an instance is created is powered on automatically. 
The only option we have is to call "Power Off" after we create an instance. I dont really like this approach and I think it would be better to let the instance to power on and remove the auto_power_on attribute from ec2 instance. What do you think?

**Comment by alonagetzler** [comment]
@alexazarh 
The best option in my opinion is to have the attribute "Auto Power On" on the deployment option but with a "True" value and read only, so it can't be changed. This will keep us consistent with other deployment options.

**Comment by alexazarh** [comment]
@alonagetzler 
I think its not possible to set an attribute as readonly when its attached to a model. You can set an attribute as readonly only for the global attribute definition. So I think we can simply remove the attribute from the deployment option and default value will be used by the setup script. Agree?

**Comment by alonagetzler** [comment]
@alexazarh agreed, i'll update the design page (and the documentation)

**Comment by alexazarh** [comment]
Will be done as part of story #106
