### ISSUE TITLE
Prepare Sandbox Connectivity command (prior to deploy)

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#7]
Add a PrepareSandboxConnectivity command to the aws shell. The command will create the VPC and subnet with the CIDR from the pool. And create the VPC peering with the management VPC. And also create a default security group for the sandbox.

This command should also create a key that will be used for all instances within the same reservation. This key should be located in an S3 bucket (the bucket will already exist and its name should be taken from an attribute named "Keypairs Location" on the AWS EC2 resource). The key name should be the reservation Id.

Notes:
- the command can only be called once from a reservation from the sandbox setup.
- if a vpc with the same reservation id tag already exist tahn throw exception
- the VPC and Subnet share the same CIDR allocated from the pool
- the default sandbox SG should allow connectivity between all instances with the same SG and allow external inbound traffic for all the management SG (taken from an attribute named "Management SG ID" on the AWS EC2) for the ports needed by QualiX and Execution Server. Need to identify the ports (QualiX ports + standard ports for installation scripts) - talk to Alex Abugov/Tomer

![img_20160601_160019](https://cloud.githubusercontent.com/assets/6730546/15804165/f8f63d12-2b08-11e6-9f5b-5269551a2feb.jpg)

The whole flow (this story is only part 3) - 
---------------
(1) Setup - gets VPC and Subnet CIDR from pool (via pool API)
pass them to

(2) PrepareSandboxConnectivity  API - gets CIDR for the VPC/Subnet from the pool + finds the AWS EC2 resource in the reservation and calls its PrepareConnectivity command, passes the VPC and Subnet CIDR

(3) PrepareSandboxConnectivity command in AWS EC2 resource validates there is no VPC with the res_id, creates the VPC and CIDR and the SG, return their info as output

**Comment by TaiTheGreat** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=154420)

**Comment by alexazarh** [comment]
We also need to create an internet gateway as part of this story. This is mandatory if we want to use public/elastic ip's
