### ISSUE TITLE
GetApplicationPorts command

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#70]
1) As a user I want to see the application ports on the deployed app.

Add a connected command to AWS EC2 Resource called GetApplicationPorts. This command will print to the output the content of the inbound/outbound ports attributes.

Output example:
============

Inbound ports:
Port 80 tcp
Ports 100-200 udp

Outbound ports: (same as inbound)

2) Print the content of the Inbound && Outbound  attributes in the app orchestration

**Comment by alexazarh** [comment]
@alonagetzler Why do we need to print this in the App Orchestration???
The App Orchestration should be generic and this feature is strongly coupled with AWS. If someone needs this during the App Orchestration or Setup than they can edit the driver accordingly...

**Comment by alonagetzler** [comment]
I do see how that will be very useful for the user, and it's won't be tied to AWS only in the future but since we do plan to show it in some "VM Properties" side pane in the next release and then it will be kind of duplicate with the output i'm OK with not showing that in the output.
