### ISSUE TITLE
Add PrepareSandboxConnectivity API

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#74]
Add an api method called PrepareSandboxConnectivity . The method will be called from the sandbox setup. The input is the reservation id. The method will:
(1) get CIDR for the VPC/Subnet from the pool and 
(2) associate the cloudprovider resource id with the reservation id using the ReservationNetworkProviders table (story http://team:8080/tfs/Quali-Collection/QualiSystems/_workitems#_a=edit&id=153888)
(3) call the PrepareSandboxConnectivity command on the cloudprovider driver for the relevant reservation.

Internal Logic:
===========
1) Scan all apps in reservation and find the cloud provider name
2) If there is no cloud providers than its OK and we exit
3) If one of the cloud provider names is not a name of a resource than throw exception
4) Check how many unique cloud providers there are that have the PrepareSandboxConnectivity command. If only one than execute this command. If more than one than throw exception. If zero than its OK and we simply exit.

Note that if there is already a CIDR allocated to the same reservation id in the pool we shouldn't allocate it again and just pass this CIDR to the PrepareSandboxConnectivity  command.

The whole flow (this story is only part 2) - 
---------------
(1) Setup - gets VPC and Subnet CIDR from pool (via pool API)
pass them to

(2) PrepareSandboxConnectivity API - gets CIDR for the VPC/Subnet from the pool + finds the AWS EC2 resource in the reservation and calls its PrepareConnectivity command, passes the VPC and Subnet CIDR

(3) PrepareSandboxConnectivity command in AWS EC2 resource validates there is no VPC with the res_id, creates the VPC and CIDR and the SG, return their info as output

**Comment by GilGald** [comment]
**Change the Name AWS EC2 to Cloud Provider Resource**

**Comment by TaiTheGreat** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=154420)
