### ISSUE TITLE
Add call to PrepareSandboxConnectivity in setup script

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#75]
If the api call throws exception setup should fail and reservation will become Active (With error) and not app should be deployed.

The whole flow (this story is only part 1) - 
---------------
(1) Setup - gets VPC and Subnet CIDR from pool (via pool API)
pass them to

(2) PrepareSandboxConnectivity API - gets CIDR for the VPC/Subnet from the pool + finds the AWS EC2 resource in the reservation and calls its PrepareSandboxConnectivity command, passes the VPC and Subnet CIDR

(3) PrepareSandboxConnectivity command in AWS EC2 resource validates there is no VPC with the res_id, creates the VPC and CIDR and the SG, return their info as output

**Comment by alonagetzler** [comment]
note that in the next version there will be more than 1 subnet in the reservation, and the information on those subnets will be part of the reservation info. the subnet(s) should be passed to the PrepareConnectivity API

**Comment by TaiTheGreat** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=154420)
