### ISSUE TITLE
Update Deploy to use the connectivity logic

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#76]
* The deployment service driver should call the pool api to request the next available ip and pass this to deploy_ami method in the aws shell
* Find the VPC with the same reservation id and use its subnet
* Find SG with the same reservation id and shared isolation level and use it - this is the default SG for the sandbox
* Remove redundant attributes from the cloud provider

If the VPC or SG with same reservation id doenst exist than fail the deployment

**Comment by alonagetzler** [comment]
note that in the next version there will be more than 1 subnet in the reservation, and the information on which subnet the app should use will be available via API (part of the reservation info)

**Comment by TaiTheGreat** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=154606)
