### ISSUE TITLE
CleanUpSandboxConnectivity API

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#78]
The teardown command will call the CleanUpSandboxConnectivity API that will do the following:
1. find the connectivity provider associated with the reservation using the table ReservationNetworkProviders (story http://team:8080/tfs/Quali-Collection/QualiSystems/_workitems/edit/153888)
2. execute command CleanUpSandboxConnectivity on the AWS EC2 with the Id found in step 1 (pass the reservation Id as input to this command, as part of a JSON object),  if there is no connectivity provider, or it has no such command than just ignore and continue

Flow:
---------
this story is about part 2 of the flow.
(1) teardown --> (2) CleanUpSandboxConnectivity API --> (3) CleanUpSandboxConnectivity command in the shell

**Comment by alexazarh** [comment]
Reservation id is actually part of the context (in the driver) that the command gets, so no need to pass it as part of the json.

**Comment by TaiTheGreat** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=154530)
