### ISSUE TITLE
organize tags for cost management

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#79]
as an administrator i want the ability to define budget rules and monitor the CloudShell usage of my AWS account using AWS tagging capability.

tags:
- CreatedBy = CloudShell
- ReservationId = (cloudshell reservation id)
- Owner = (name of the reservation owner)
- Domain = (name of the reservation's domain)
- Blueprint = (name of the reservation's environment)

the tags should be associated with all the entities we create in AWS and can have tags - instance, security group, VPC, Subnet, AMIs, Key Pairs, Network Interface, storage disk, storage bucket etc.

how to demo:
1. have a blueprint with an app and the OOB setup and teardown
2. reserve the blueprint
3. see the app being deployed
4. open AWS and view the instance tags - see that tags defined above with all the correct information filled in.

**Comment by TaiTheGreat** [comment]
@alonagetzler  Owner appears instead of "User".  Assume this is ok?

**Comment by alonagetzler** [comment]
@TaiTheGreat that's OK. please update the story so we won't forget to update the document it correctly.

**Comment by TaiTheGreat** [comment]
Updated.
