### ISSUE TITLE
Support Public and Elastic IPs

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/AWS-Shell#81]
As an app designer I want my app to have a public or elastic IP

We need to have two new attributes on the deployment service - (1) Add Public IP (true/false, default should be false) and (2) Add Elastic IP (string, empty by default). We also need a new attribute called "Public IP" (string, empty by default) on the generic deployed app model.

"Add Public IP" = True
"Add Elastic IP" = empty
--> assign dynamic public IP + return the public IP in the VM properties + populate the "Public IP" attribute on the deployed app with the public IP value

"Add Public IP" = True
"Add Elastic IP" = non empty
--> assign dynamic public IP and an elastic IP + return both the public IP and elastic IP in the VM properties + populate the "Public IP" attribute on the deployed app with the elastic IP value

"Add Public IP" = False
"Add Elastic IP" = empty
--> do nothing!

"Add Public IP" = False
"Add Elastic IP" = non empty
--> assign elastic IP + return the elastic IP in the VM properties + populate the "Public IP" attribute on the deployed app with the elastic IP value

Note that we should assign a private IP to all the deployed apps, and this IP should be populated as the deployed app address.

**Comment by alonagetzler** [comment]
updated the logic in the story. hopefully it's clearer now. the changes are around the fact that we assign both public & elastic when user requires both, and return them in the VM properties.

**Comment by alexazarh** [comment]
We cannot use an elastic ip if we dont have an internet gateway. 
I will add the creation of an internet gateway to prepare connectivity
