### ISSUE TITLE
SG not removed when deleting instance

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#83]

**Comment by tornizanQ** [comment]
I can still see the SG after the machine is terminated in SG TAB in AWS
Is there some delay between the termination of a machine to the delete of SG?

**Comment by alonagetzler** [comment]
only deletion of an AWS instance via CloudShell should prompt deletion of its dedicated SG. if you terminate the instance via AWS directly i guess it won't delete the SG and that's OK.

**Comment by tornizanQ** [comment]
Still reproduces
