### ISSUE TITLE
Add call to CleanupConnectivityCommand in teardwon script

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#88]
Add call to CleanupConnectivityCommand testshell api in the end of the teardown

Flow:
---------
this story is about part 1 of the flow.
(1) teardown --> (2) CleanUpSandboxConnectivity API --> (3) CleanupSandboxConnectivity command in the shell

**Comment by TaiTheGreat** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=154530)
