### ISSUE TITLE
Update description in the vCenter DataModel

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#89]
Update description in the vCenter DataModel

VM Resource Pool – Resource pool in which the virtual machine is created. Leave this field empty if you specified a specific host name in the VM cluster field.

VM Cluster – vCenter cluster or host to use when deploying a virtual machine (datastore cluster or hostname). If empty, the cluster defined in the vCenter resource is used. If a cluster a selected than the “VM Resource Pool” parameter must be populated with a host name.

**Comment by razaba** [comment]
by the way...
VM Resource Pool: is not mandatory

**Comment by alexazarh** [comment]
The suggest description in this issue is not correct.
